ASP_PROFTAAK/ASP_PROFTAAK/Controllers/ToegangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASP_PROFTAAK.App_DAL;
using ASP_PROFTAAK.Models;

namespace ASP_PROFTAAK.Controllers
{
    public class ToegangController : Controller
    {
        ToeganRepository tr = new ToeganRepository(new ToegansSqlContext());
        // GET: Toegang
        public ActionResult Index(int eventid)
        {
            List<Aanwezig> aanwezigen = tr.GetAllAanwezig(eventid);
           
            return View(aanwezigen);
        }

        [HttpPost]
        public ActionResult ChangeAanwezigheid(int eventid, string barcode)
        {
            tr.ChangeAanwezigheid(eventid, barcode);
            return RedirectToAction("Index", "toegang", new { eventid });
        }


        [HttpPost]
        public ActionResult BrengPolsbandjeTerug(int eventid, string barcode)
        {
            tr.BrengPolsbandjeTerug(barcode);
            return RedirectToAction("Index", "toegang", new { eventid });
        }

        // GET: Toegang/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Toegang/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Toegang/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Toegang/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Toegang/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Toegang/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ASP_PROFTAAK/ASP_PROFTAAK/Views/Toegang/Index.cshtml
@model IEnumerable<ASP_PROFTAAK.Models.Aanwezig>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Bezoekers van het evenement</h2>

<table class="table">
    <tr>
        <th>
            Aanwezig
        </th>
        <th>
            Barcode polsbandje
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Voornaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tussenvoegsel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Achternaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TelefoonNummer)
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @if ((int)item.AanwezigopEvent == 1)
                {
                    <input type="checkbox" disabled="disabled" checked>
                }
                else
                {
                    <input type="checkbox" disabled="disabled">
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Barcode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Voornaam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tussenvoegsel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Achternaam)
            </td>
            <td>
                0 @Html.DisplayFor(modelItem => item.TelefoonNummer)
            </td>
            <td>

                @using (Html.BeginForm("ChangeAanwezigheid", "Toegang", new {eventid = item.EventId, barcode = item.Barcode}))
                {
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" name="ChangeAanwezigheid" value="Verander aanwezigheid" class="btn btn-default"/>
                        </div>
                    </div>
                }
            </td>
            <td>
                @using (Html.BeginForm("BrengPolsbandjeTerug", "Toegang", new {eventid = item.EventId, barcode = item.Barcode}))
                {
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" name="BrengPolsbandjeTerug" value="Polsbandje retourneren" class="btn btn-default"/>
                        </div>
                    </div>
                }
            </td>
        </tr>
    }

</table>


@Html.ActionLink("Terug naar evenementen", "index", "Event")