ASP_PROFTAAK/ASP_PROFTAAK/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ASP_PROFTAAK.Models
{
    public class Event
    {
        private int id;
        private int locatie_id;

        private string naam;
        private DateTime datumStart;
        private DateTime datumEinde;
        private int maxBezoekers;

        [Required(ErrorMessage = "Required")]
        public int Id { get { return id; } set { id = value; } }
        [Required(ErrorMessage = "Required")]
        public int Locatie_id { get { return locatie_id; } set { locatie_id = value; } }
        [Required(ErrorMessage = "Required")]
        public string Naam { get { return naam; } set { naam = value; } }
        [DisplayName("Start datum")]
        public DateTime DatumStart { get { return datumStart; } set { datumStart = value; } }
        [Required(ErrorMessage = "Required")]
        [DisplayName("Eind datum")]
        public DateTime DatumEinde { get { return datumEinde; } set { datumEinde = value; } }
        [Required(ErrorMessage = "Required")]
        public int MaxBezoekers { get { return maxBezoekers; } set { maxBezoekers = value; } }

        public Event()
        {

        }

        public Event(int id, int locatie_id, string naam, DateTime datumStart, DateTime datumEinde, int maxBezoekers)
        {
            this.id = id;
            this.locatie_id = locatie_id;
            this.naam = naam;
            this.datumStart = datumStart;
            this.datumEinde = datumEinde;
            this.maxBezoekers = maxBezoekers;
        }
        public Event(int locatie_id, string naam, DateTime datumStart, DateTime datumEinde, int maxBezoekers)
            : this(-1, locatie_id, naam, datumStart, datumEinde, maxBezoekers)
        {

        }
        public override string ToString()
        {
            return naam + " || " + datumStart + " - " + datumEinde + " || " + maxBezoekers;
        }


    }
}

ASP_PROFTAAK/ASP_PROFTAAK/Models/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASP_PROFTAAK.Models
{
    public class EventViewModel
    {
        public Event event1 { get; set; }
        public Locatie locatie { get; set; }
        //public Plek plek { get; set; }
        //public Specificatie spec { get; set; }

    }
}

ASP_PROFTAAK/ASP_PROFTAAK/Models/Locatie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASP_PROFTAAK.Models
{
    public class Locatie
    {
        private int id;
        private string naam;
        private string straat;
        private string nummer;
        private string postcode;
        private string plaats;
        public string NullString = "Geen Invoer";

        public int Id { get { return id; } set { id = value; } }
        public string Naam { get { return naam; } set { naam = value; } }
        public string Straat { get { return straat; } set { straat = value; } }
        public string Nummer { get { return nummer; } set { nummer = value; } }
        public string Postcode { get { return postcode; } set { postcode = value; } }
        public string Plaats { get { return plaats; } set { plaats = value; } }

        public Locatie(int id, string naam, string straat, string nummer, string postcode, string plaats)
        {
            this.Id = id;
            this.Naam = naam;
            this.Straat = straat;
            this.Nummer = nummer;
            this.Postcode = postcode;
            this.Plaats = plaats;
        }

        public Locatie(string naam, string straat, string nummer, string postcode, string plaats) : this(-1, naam, straat, nummer, postcode, plaats)
        {
            this.Id = 0;
            this.Naam = naam;
            this.Straat = straat;
            this.Nummer = nummer;
            this.Postcode = postcode;
            this.Plaats = plaats;
        }



        private void addPlek()
        {

        }
    }
}

ASP_PROFTAAK/ASP_PROFTAAK/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASP_PROFTAAK.App_DAL;
using ASP_PROFTAAK.Models;

namespace ASP_PROFTAAK.Controllers
{
    public class EventController : Controller
    {
        EventRepository eventrepo = new EventRepository(new EventSQLContext());
        LocatieRepository locrepo = new LocatieRepository(new LocatieSQLContext());
        PlekRepository plekrepo = new PlekRepository(new PlekSQLContext());
        SpecificatieRepository specrepo = new SpecificatieRepository(new SpecificatieSQLContext());
        List<List<Specificatie>> specifications = new List<List<Specificatie>>();
        List<Specificatie> specification = new List<Specificatie>();
        // GET: Event
        public ActionResult Index()
        {
            List<Event> events = eventrepo.GetAllEvents();
            List<Locatie> locaties = new List<Locatie>();
            foreach (Event item in events)
            {
                locaties.Add(locrepo.GetByEvent(item));
            }
            var viewmodel = new EventLocationViewModel()
            {
                events = events,
                locaties = locaties
            };
            return View(viewmodel);
        }

        //GET: EventView
        /* public ActionResult EventView()
         {
             List<Event> events = eventrepo.GetAllEvents();
             List<Locatie> locaties = locrepo.GetAllLocations();
             List<Plek> plekken = plekrepo.GetAll();
             List<Specificatie> specs = specrepo.GetAll();

             var viewModel = new EventViewModel
             {
                 locatie = locaties,
                 event1 = events,
                 plek = plekken,
                 spec = specs
             };
             return View(viewModel);
         }*/

        // GET: Event/Details/5
        public ActionResult Details(int id)
        {
            Event events = eventrepo.GetByID(id);
            Locatie locatie1 = locrepo.GetByEvent(events);
            var Viewmodel = new EventViewModel()
            {
                event1 = events,
                locatie = locatie1
            };
            if (events != null)
            {
                return View(Viewmodel);
            }
            else return HttpNotFound();
        }


        public ActionResult Locaties()
        {
            List<Locatie> locaties = locrepo.GetAllLocations();
            return View(locaties);
        }


        // GET: Event/Create
        public ActionResult Create()
        {
            Event events = new Event();
            List<Locatie> locaties = locrepo.GetAllLocations();
            List<SelectListItem> locatieItems = new List<SelectListItem>();

            foreach (Locatie locatie in locaties)
            {
                locatieItems.Add(new SelectListItem { Text = locatie.Naam, Value = Convert.ToString(locatie.Id) });
            }


            ViewBag.category = locatieItems;
            ViewData["locatie"] = new SelectList(locrepo.GetAllLocations(), "Id", "Naam");

            return View(events);

        }

        // POST: Event/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection) //validation fixen, de requireds in de event model werken niet
        {

            // TODO: Add insert logic here
            ViewData["locatie"] = new SelectList(locrepo.GetAllLocations(), "Id", "Naam");// nog een keer lijst aanroepen anders vind de view de viewdata niet

            string locatie = Request.Form["locatie"].ToString();
            DateTime DateTimeStart = Convert.ToDateTime(collection["DatumStart"]);
            string DateStart = DateTimeStart.Date.ToString();
            DateTime DateTimeEinde = Convert.ToDateTime(collection["DatumStart"]);
            string DateEinde = DateTimeEinde.Date.ToString();

            if (string.IsNullOrEmpty(locatie))
            {
                
                Event events = new Event(0, collection["Naam"], Convert.ToDateTime(DateStart), Convert.ToDateTime(DateEinde), Convert.ToInt32(collection["MaxBezoekers"]));
                if (ModelState.IsValid)
                {
                    eventrepo.InsertEvent(events);
                    return RedirectToAction("Index");

                }
            }
            else
            {
                int locatieId = Convert.ToInt32(locatie);
                Event events = new Event(locatieId, collection["Naam"], Convert.ToDateTime(DateStart), Convert.ToDateTime(DateEinde), Convert.ToInt32(collection["MaxBezoekers"]));
                if (ModelState.IsValid)
                {
                    eventrepo.InsertEvent(events);
                    return RedirectToAction("Index");

                }
            }





            return View();





        }

        // GET: Event/Edit/5
        public ActionResult Edit(int id)
        {
            List<Locatie> locaties = locrepo.GetAllLocations();
            List<SelectListItem> locatieItems = new List<SelectListItem>();

            foreach (Locatie locatie in locaties)
            {
                locatieItems.Add(new SelectListItem { Text = locatie.Naam, Value = Convert.ToString(locatie.Id) });
            }


            ViewBag.category = locatieItems;
            ViewData["locatie"] = new SelectList(locrepo.GetAllLocations(), "Id", "Naam");
            Event events = eventrepo.GetByID(id);
            if (events != null)
            {
                return View(events);
            }
            else return HttpNotFound();

        }



        // POST: Event/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            ViewData["locatie"] = new SelectList(locrepo.GetAllLocations(), "Id", "Naam");// nog een keer lijst aanroepen anders vind de view de viewdata niet
            string locatie = Request.Form["locatie"].ToString();

            Event events = new Event(Convert.ToInt32(locatie), collection["Naam"], Convert.ToDateTime(collection["datumStart"]), Convert.ToDateTime(collection["datumEinde"]), Convert.ToInt32(collection["maxBezoekers"]));
            
                // TODO: Add update logic here

                eventrepo.UpdateEvent(id, events);
                return RedirectToAction("Index");
           
            
                
            
        }

        //get
        public ActionResult EditLocatie(int id)
        {
            Locatie locaties = locrepo.GetLocatieById(id);
            return View(locaties);
        }
        //post
        [HttpPost]
        public ActionResult EditLocatie(int id, FormCollection collection)
        {
            Locatie locatie = new Locatie(id, collection["Naam"], collection["Straat"], collection["Nummer"], collection["Postcode"], collection["Plaats"]);
            try
            {
                locrepo.UpdateLocatie(locatie);
                return RedirectToAction("EditLocatie");
                
            }
            catch
            {
                return HttpNotFound();
            }




        }

        // GET: Event/Delete/5
        public ActionResult Delete(int id)
        {
            Event events = eventrepo.GetByID((id));
            return View(events);
        }

        // POST: Event/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            
                eventrepo.DeleteEvent((id));
                return RedirectToAction("locaties");
           
        }


        // GET: Event/Delete/5
        public ActionResult DeleteLocatie(int id)
        {
            Locatie locatie = locrepo.GetLocatieById(id);
            return View(locatie);
        }

        // POST: Event/Delete/5
        [HttpPost]
        public ActionResult DeleteLocatie(int id, FormCollection collection)
        {

            eventrepo.DeleteLocatie(id);
            return RedirectToAction("Locaties");

        }




        //Get locatie
        public ActionResult AddLocation()
        {

            return View();
        }





        [HttpPost]
        //post AddLocatie with plekken
        public ActionResult AddLocation(FormCollection collection)
        {
            Locatie locatie = new Locatie(collection["locatie.Naam"], collection["locatie.Straat"], collection["locatie.Nummer"], collection["locatie.Postcode"], collection["locatie.Plaats"]);
            int plekAmount = Convert.ToInt32(collection["plekAmount"]);
            locrepo.InsertLocatie(locatie);

            int lastInsertedLocationId = locrepo.GetLocatieId();


            for (int i = 1; i <= plekAmount; i++)//voor het ingegeven aantal plekken genereren
            {
                int x = 1;//huisnummers
                Plek plek = new Plek(lastInsertedLocationId, Convert.ToString(x), 0);
                plekrepo.InsertPlek(plek);
                x++;
            }

            return RedirectToAction("Locaties");
        }

        //get
        public ActionResult EditPlekken(int id)
        {

            if (id != 0)
            {
                List<Plek> plekken = plekrepo.GetPlekByLocatieId(id);
                foreach (Plek plek in plekken)
                {
                    specification = specrepo.GetAllSpecificatieByPlekId(plek.ID);
                    specifications.Add(specification);
                }
                var viewmodel = new PlekSpecificatieViewModel()
                {
                    plekken = plekken,
                    specificaties = specifications

                };
                return View(viewmodel);
            }
            else
            {
                int lastInsertedLocationId = locrepo.GetLocatieId();
                List<Plek> plekken = plekrepo.GetPlekByLocatieId(lastInsertedLocationId);
                return View(plekken);
            }
        }

        [HttpPost]
        public ActionResult EditPlekken(List<Plek> plekken)
        {

ASP_PROFTAAK/ASP_PROFTAAK/Controllers/LocatieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASP_PROFTAAK.Controllers
{
    public class LocatieController : Controller
    {
        // GET: Locatie
        public ActionResult Index()
        {
            return View();
        }

        // GET: Locatie/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Locatie/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Locatie/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Locatie/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Locatie/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Locatie/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Locatie/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ASP_PROFTAAK/ASP_PROFTAAK/Views/Event/AddLocation.cshtml
@model ASP_PROFTAAK.Models.LocatiePlekViewModel

@{
    ViewBag.Title = "AddLocation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Voeg locatie toe</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.locatie.Naam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.locatie.Naam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.locatie.Naam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.locatie.Straat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.locatie.Straat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.locatie.Straat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.locatie.Nummer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.locatie.Nummer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.locatie.Nummer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.locatie.Postcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.locatie.Postcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.locatie.Postcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.locatie.Plaats, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.locatie.Plaats, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.locatie.Plaats, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Aantal plekken</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.plekAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.plekAmount, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @*<input type="button" class="btn btn-info" value="Create locatie" onclick="location.href='@Url.Action("EditPlekken", "Event")'" />*@
                <input type="submit" class="btn btn-info" value="Create locatie" />

            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Event overzicht", "Index") |
    @Html.ActionLink("Locatie overzicht", "Locaties") |
    @Html.ActionLink("Terug naar maak een event", "Create")

</div>

ASP_PROFTAAK/ASP_PROFTAAK/Views/Event/Create.cshtml
@model ASP_PROFTAAK.Models.Event

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Maak een event</h2>

@using (Html.BeginForm())
{
    Html.EnableClientValidation(true);

    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Naam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumStart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumEinde, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumEinde, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumEinde, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxBezoekers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxBezoekers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxBezoekers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Locatie toevoegen</label>
            <div class="col-md-10">
                @Html.DropDownList("locatie", null, "select locatie", new { @class = "dropdown" })
                @Html.ActionLink("Add een nieuwe locatie", "AddLocation")

            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar het overzicht", "Index")

</div>

ASP_PROFTAAK/ASP_PROFTAAK/Views/Event/Delete.cshtml
@model ASP_PROFTAAK.Models.Event

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Locatie_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Locatie_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Naam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumStart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumEinde)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumEinde)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxBezoekers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxBezoekers)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ASP_PROFTAAK/ASP_PROFTAAK/Views/Event/DeleteLocatie.cshtml
@model ASP_PROFTAAK.Models.Locatie

@{
    ViewBag.Title = "DeleteLocatie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DeleteLocatie</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Locatie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Straat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Straat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nummer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nummer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Postcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Postcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Plaats)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Plaats)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ASP_PROFTAAK/ASP_PROFTAAK/Views/Event/EditPlekken.cshtml
@model ASP_PROFTAAK.Models.PlekSpecificatieViewModel

@{
    ViewBag.Title = "EditPlekken";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit de eigenschappen van de plekken</h2>

@using (Html.BeginForm("EditPlekken", "Event", FormMethod.Post))
{
    <table class="table">

        <tr>
            <td>
                ID (disabled)
            </td>
            <td>
                Locatie ID (disabled)
            </td>
            <td>
                Huisnummmer
            </td>
            <td>
                Capaciteit
            </td>
            <td>
                Specificatie
            </td>
        </tr>


        @for (int i = 0; i < Model.plekken.Count; i++)
        {
            <tr>
                <td>

                    @Html.TextBox("plekken[" + @i + "].ID", Model.plekken[i].ID, new {@readonly = "readonly"})
                </td>
                <td>
                    @Html.TextBox("plekken[" + @i + "].LocatieId", Model.plekken[i].LocatieId, new {@readonly = "readonly"})
               
                
                <td>
                    @Html.TextBox("plekken[" + @i + "].Nummer", Model.plekken[i].Nummer)
                </td>
                <td>
                    @Html.TextBox("plekken[" + @i + "].Capaciteit", Model.plekken[i].Capaciteit)
                </td>
                <td>
                    @foreach (var item in Model.specificaties[i])
                    {
                        
                            
                        @Html.TextBoxFor(model => item.Naam) 
                        

                    }
                </td>
                        
            </tr>
        }

        <tr>
            <td colspan="4">
                <input type="submit" value="Submit" />
            </td>
        </tr>
    </table>
}

ASP_PROFTAAK/ASP_PROFTAAK/Views/Event/Index.cshtml
@model ASP_PROFTAAK.Models.EventLocationViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
@using (Html.BeginForm("edit", "Event", FormMethod.Post))
{

    <p>
        @*@if((int)Session["UserId"] == 1)
            {
            @Html.ActionLink("Create New", "Create")
            }*@
    </p>
    <table class="table">
        <tr>

            <th>
                @Html.DisplayNameFor(model => Model.Event.Naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Event.DatumStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Event.DatumEinde)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Event.MaxBezoekers)
            </th>

            <th></th>

        </tr>

        @foreach (var item in Model.events)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Naam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumStart)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumEinde)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxBezoekers)
                </td>
                @if (Convert.ToInt32(Session["userid"]) > 0)
                {
                    <td>
                        @if (Convert.ToInt32(Session["userid"]) == 1)
                        {

                            @Html.ActionLink("Edit", "Edit", "Event", new {id = item.Id}, null) 
                            @Html.ActionLink("Details", "Details", new {id = item.Id}) 
                            @*@Html.ActionLink("Delete", "Delete", new {id = item.Id})*@ 
                            @Html.ActionLink("Aanwezigheid", "Index", "Toegang", new {eventid = item.Id}, null) 
                        }
                        @Html.ActionLink("Reservering maken", "Create", "Reservering", new { id = item.Id }, null)
                    </td>
                }

            </tr>
        }
        @if (Convert.ToInt32(Session["userid"]) == 1)
        {
            @Html.ActionLink("Event maken", "Create", "Event", null)

        }


    </table>


}

ASP_PROFTAAK/ASP_PROFTAAK/Views/Event/Locaties.cshtml
@model IEnumerable<ASP_PROFTAAK.Models.Locatie>

@{
    ViewBag.Title = "Locaties";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Locaties</h2>

<p>
    @Html.ActionLink("Locatie toevoegen", "AddLocation")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Naam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Straat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nummer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Postcode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Plaats)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Straat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nummer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Postcode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Plaats)
            </td>
            <td>
                @Html.ActionLink("Edit locatie", "Editlocatie", new { id = item.Id }) |
                @Html.ActionLink("Edit plekken", "EditPlekken", new { id = item.Id }) |
                @Html.ActionLink("Delete locatie", "DeleteLocatie", new { id = item.Id })
            </td>
        </tr>
    }

</table>